TimeTravelAgency/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TimeTravelAgency.Domain.Entity;
using TimeTravelAgency.Domain.Enum;
using TimeTravelAgency.Domain.ViewModels.Cart;
using TimeTravelAgency.Service.Interfaces;

namespace TimeTravelAgency.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ITourService _tourService;
        private readonly IPictureService _pictureService;

        public CartController(IOrderService orderService, ITourService tourService, IPictureService pictureService)
        {
            _orderService = orderService;
            _tourService = tourService;
            _pictureService = pictureService;
        }

        [HttpPost, HttpGet]
        public async Task<IActionResult> GetCart(int userId)
        {
            var response = await _orderService.GetOrders(userId);
            if (response.Data == null)
            {
                return View();
            }

            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                var response_picture = await _pictureService.GetPictures(ViewName.Tour);
                if (response_picture.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    if (response.Data != null)
                    {
                        OrdersWithPicturesViewModel ordersWithPictures = new OrdersWithPicturesViewModel()
                        {
                            orders = response.Data.ToList(),
                            pictures = new Dictionary<string, Picture>()
                        };

                        if (response_picture.Data != null)
                            foreach (var pic in response_picture.Data)
                            {
                                ordersWithPictures.pictures.Add(pic.Title, pic);
                            }
                        //using (var pic = response_picture.Data.GetEnumerator())
                        //{
                        //    while (pic.MoveNext())
                        //    {
                        //        ordersWithPictures.pictures.Add(pic.Current.Title, pic.Current);
                        //    }

                        //}
                        return View(ordersWithPictures);
                    }

                }
                return View();
            }
            return RedirectToAction("Error", "Shared");
        }

        public async Task<IActionResult> DeleteTourFromCart(int id)
        {
            var response = await _orderService.DeleteOrderById(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetCart", new { userId = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value) });
            }
            return RedirectToAction("Error", "Shared");
        }
    }
}

TimeTravelAgency/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using TimeTravelAgency.Service.Interfaces;
using TimeTravelAgency.Domain.ViewModels.Profile;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TimeTravelAgency.Domain.Entity;
using TimeTravelAgency.Service.Implementations;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace TimeTravelAgency.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IProfileService _profileService;

        public ProfileController(IProfileService profileService)
        {
            _profileService = profileService;
        }

        [HttpGet]
        public async Task<IActionResult> EditProfile(int id)
        {
            var response = await _profileService.GetProfileById(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error", "Shared");
        }
        [HttpPost]
        public async Task<IActionResult> EditProfile(int id, ProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                Uprofile profile = new Uprofile
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Age = model.Age,
                    Email = model.Email,
                    Phone = model.Phone,
                    Uaddress = model.Uaddress
                };

                var response = await _profileService.Edit(id, profile);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            return RedirectToAction("Error", "Shared");
        }
    }
}

TimeTravelAgency/Controllers/TourController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using TimeTravelAgency.Domain.Entity;
using TimeTravelAgency.Domain.Enum;
using TimeTravelAgency.Domain.ViewModels.TourViewModels;
using TimeTravelAgency.Service.Interfaces;

namespace TimeTravelAgency.Controllers
{
    public class TourController : Controller
    {
        private readonly ITourService _tourService;
        private readonly IPictureService _pictureService;

        public TourController(ITourService tourService, IPictureService pictureService)
        {
            _tourService = tourService;
            _pictureService = pictureService;
        }

        [HttpGet]
        public async Task<IActionResult> GetTours()
        {
            var response = await _tourService.GetTours();
            var response_picture = await _pictureService.GetPictures(ViewName.Tour);

            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                if (response_picture.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    ToursWithPicturesViewModel tourWithPictures = new ToursWithPicturesViewModel()
                    {
                        tours = response.Data.ToList(),
                        pictures = new Dictionary<string, Picture>()
                    };

                    if (response_picture.Data != null)
                        using (var pic = response_picture.Data.GetEnumerator())
                        {
                            while (pic.MoveNext())
                            {
                                tourWithPictures.pictures.Add(pic.Current.Title, pic.Current);
                            }

                        }

                    return View(tourWithPictures);
                }

            }

            return RedirectToAction("Error", "Shared");
        }
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> CreateTour()
        {
            return PartialView();
        }

        private void setByteArray(Picture pic, in IFormFile uploadImage)
        {
            if (uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)uploadImage.Length);
                }
                // установка массива байтов
                pic.Image = imageData;
            }
        }

        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        public async Task<IActionResult> CreateTour(Tour tour, IFormFile uploadImage)
        {
            var response = await _tourService.CreateTour(tour);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                Picture pic = new Picture() { ViewName = ViewName.Tour, Title = string.Format("{0}-main", tour.Id) };

                if (uploadImage != null)
                {
                    setByteArray(pic, uploadImage);

                    //ViewBag.Picture
                }

                var response_pic = await _pictureService.CreatePicture(pic);
                if (response_pic.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("GetTours");
                }

            }

            return RedirectToAction("Error", "Shared");
        }

        [Authorize(Roles = "Admin, Moderator")]
        [HttpGet]
        public async Task<IActionResult> UpdateTour(int id)
        {
            var response = await _tourService.GetTourById(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return PartialView(response.Data);
            }

            return RedirectToAction("Error", "Shared");

        }

        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        public async Task<IActionResult> UpdateTour(int id, Tour tour, IFormFile uploadImage)
        {
            var response = await _tourService.Edit(id, tour);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                Picture pic = new Picture() { ViewName = ViewName.Tour, Title = string.Format("{0}-main", tour.Id) };
                if (uploadImage != null)
                {
                    setByteArray(pic, uploadImage);

                    //ViewBag.Picture
                    var response2 = await _tourService.GetTourById(id);
                    var response_pic = await _pictureService.GetPictureByTitle(string.Format("{0}-main", response2.Data.Id));
                    if (response_pic.StatusCode == Domain.Enum.StatusCode.OK)
                    {
                        pic.Title = response_pic.Data.Title;
                        var response_pic2 = await _pictureService.Edit(response_pic.Data.Id, pic);
                        if (response_pic2.StatusCode == Domain.Enum.StatusCode.OK)
                        {
                            return RedirectToAction("GetTours");
                        }
                    }
                }
                return RedirectToAction("GetTours");
            }

            return RedirectToAction("Error", "Shared");
        }

        [Authorize(Roles = "Admin, Moderator")]
        [HttpGet]
        public async Task<IActionResult> DeleteTour(int id)
        {
            var response = await _tourService.GetTourById(id);
            var response2 = await _tourService.DeleteTourById(id);
            if (response2.StatusCode == Domain.Enum.StatusCode.OK)
            {
                var response_pic = await _pictureService.DeletePictureByTitle(string.Format("{0}-main", response.Data.Id));
                if (response_pic.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("GetTours");
                }
            }
            return RedirectToAction("Error", "Shared");
        }

        public async Task<IActionResult> TourInfo(int id)
        {
            var response = await _tourService.GetTourById(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                TourWithPicturesViewModel tourWithPictures = new TourWithPicturesViewModel()
                {
                    tour = response.Data,
                    pictures = new Dictionary<string, Picture>()
                };

                var response_pic = await _pictureService.GetPictures(ViewName.Tour);
                if (response_pic.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    if (response_pic.Data != null)
                        using (var pic = response_pic.Data.GetEnumerator())
                        {
                            while (pic.MoveNext())
                            {
                                tourWithPictures.pictures.Add(pic.Current.Title, pic.Current);
                            }

                        }

                    return View(tourWithPictures);
                }

            }

            return RedirectToAction("Error", "Shared");
        }

    }
}

TimeTravelAgency/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeTravelAgency</title>

    <link rel="shortcut icon" href="~/images/icon/logo_icon.png" type="image/png">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/img&icon.css" />
    <link rel="stylesheet" href="~/js/site.js" />
    <link rel="stylesheet" href="~/TimeTravelAgency.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-md fixed-top border-bottom" style="background-color: white">
            <div class="container-fluid d-flex flex-nowrap justify-content-between mx-5">

                <div>
                    <a class="navbar-brand icon-size" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="@Url.Content("~/images/icon/logo_icon.png")" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                        ChronoVoyage
                    </a>
                </div>

                <div class="m-auto">
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link underline-nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link underline-nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TravelGuide">Путеводитель</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link underline-nav-link text-dark" asp-area="" asp-controller="Tour" asp-action="GetTours">Туры</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link underline-nav-link text-dark text-nowrap" asp-area="" asp-controller="Home" asp-action="About">О нас</a>
                                </li>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {

                                    <li class="nav-item">
                                        <a class="nav-link underline-nav-link text-dark" asp-area="" asp-controller="Account" asp-action="GetUsers">Управление аккаунтами</a>
                                    </li>

                                }
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="d-inline-flex align-items-center flex-nowrap">
                    <div>
                        <a class="navbar-brand" href="/"><img class="icon-size" src="@Url.Content("~/images/icon/search_icon.png")" alt="search" /></a>
                    </div>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <form method="post" asp-controller="Cart" asp-action="GetCart" asp-route-userId="@Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value)">
                            <input type="image" class="icon-size mt-2" src="@Url.Content("~/images/icon/shop_cart_icon.png")" alt="cart" />
                        </form>

                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img class="icon-size m-0" src="@Url.Content("~/images/icon/account_icon.png")" alt="login" />
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" asp-controller="Profile" asp-action="EditProfile" asp-route-id="@Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value)">Изменить профиль</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <form class="dropdown-item" method="post" asp-controller="Account" asp-action="Logout">
                                        <input class="no-back-border" type="submit" value="Выход" />
                                    </form>
                                </li>
                            </ul>
                        </div>
                    }

                    else
                    {
                        <div>
                            <a class="navbar-brand me-3" href="/"><img class="icon-size" src="@Url.Content("~/images/icon/shop_cart_icon.png")" alt="cart" /></a>
                        </div>
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle px-0 pt-2 pb-1" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img class="icon-size m-0" src="@Url.Content("~/images/icon/login_icon.png")" alt="login" />
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Login">Войти</a></li>
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Register">Зарегистрироваться</a></li>
                            </ul>
                        </div>
                    }

                </div>

                <button class="navbar-toggler navbar-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>

    </header>
    <div class="container-fluid no-mp">
        <main role="main" class="pb-3">
            @RenderBody()
            <div class="container" style="height:50vh"></div>
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white pt-5 pb-2">
        <div class="container">
            <div class="container-fluid text-center">
                <h4>ChronoVoyage</h4>
            </div>
            <div class="py-2">
                <div class="row justify-content-between">
                    <div class="col-4">
                        <h5 class="pb-4">ПРИСОЕДИНЯЙТЕСЬ К СЕМЬЕ</h5>
                        <div class="text-wrap" style="line-height:2">
                            <p>
                                Подпишитесь, чтобы получить ранний доступ к нашим эксклюзивным предложениям, таким как будущие продажи архивов,
                                только для подписчиков
                            </p>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="container text-wrap">
                            <div class="row">
                                <div class="col-4">
                                    <div class="col">
                                        <p>ОБЩЕЕ</p>
                                    </div>
                                    <div class="col pb-3 fs-small" style="line-height:2">
                                        <a class="text-decoration-none link-dark" style="color:black" href="#">СВЯЗАТЬСЯ С НАМИ</a>
                                    </div>
                                    <div class="col fs-small">
                                        <a class="text-decoration-none link-dark" asp-controller="Home" asp-action="About">О НАС</a>
                                    </div>
                                </div>
                                <div class="col-4">
                                    <div class="col">
                                        ПОДДЕРЖКА
                                    </div>
                                    <div class="col py-3 fs-small" style="line-height:2">
                                        <a class="text-decoration-none link-dark" style="color:black" href="#">ВОПРОСЫ И ВОЗВРАТЫ</a>
                                    </div>
                                    <div class="col fs-small" style="line-height:2">
                                        <a class="text-decoration-none link-dark" asp-controller="Home" asp-action="Privacy">ПОЛИТИКА КОНФЕДЕНЦИАЛЬНОСТИ</a>
                                    </div>
                                </div>
                                <div class="col-4">
                                    <div class="col">
                                        СОЦ СЕТИ
                                    </div>
                                    <div class="col fs-small">
                                        <a class="text-decoration-none link-dark" style="color:black" href="#">ВКОНТАКТЕ</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid text-center">
                &copy; 2024 ChronoVoyage
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>